### ISSUE TITLE
[Help Wanted] fix icon alignment

### ISSUE THREAD

**Issue by tylim88** [zero-to-mastery/GameSenshi#37]
![image](https://user-images.githubusercontent.com/5227509/67165222-15177600-f3b5-11e9-93a9-605d5d937c99.png)
![image](https://user-images.githubusercontent.com/5227509/67165257-9cfd8000-f3b5-11e9-961f-af08fa040011.png)
![image](https://user-images.githubusercontent.com/5227509/67165251-8d7e3700-f3b5-11e9-88ed-dd2b3b145912.png)

At `localhost:3000/profile`, when you playing the sample audio, the icon appearance switch every 1 second, notice that the icon is slightly misaligned for each switch

the component is src/componentAtoms/ButtonSound
appreciate if anyone can provide solution to this issue

**Comment by tylim88** [comment]
this seems to be unsolvable, because those are svg

**Comment by HopeEternal** [comment]
@tylim88 I actually had some ideas on how to fix this, I just wasn't sure about execution:

1. The first idea was manipulating the View Box property for each SVG as it's called via React (I've never done this before and have no idea how to go about it)
2. The Second is manually adding different padding or margin to the icon container in the logic statement in which React displays each one
3. The easiest is to simply use different icons, possibly svg's saved to the GameSenshi assets that have the alignment fixed in the image itself

**Comment by tylim88** [comment]
option 1 and option 2 is not a reliable fix, especially when you change the icon

I think the best it to find new icon or some gif icon that are made for this purpose
