### ISSUE TITLE
[BUG] Play Button Icon and Text Overlap on Mobile

### ISSUE THREAD

**Issue by HopeEternal** [zero-to-mastery/GameSenshi#49]
#### Issue description
On the http://localhost:3000/profile page, the Play Button icon and timestamp text overlap on smaller screen sizes. 

I suggest either expanding the width of the button or removing clip length on Mobile.

#### Steps to reproduce the issue
1. Access profile page
2. Resize browser window down to smaller size

#### Screenshot
![image](https://user-images.githubusercontent.com/42893634/69464746-70ce7980-0d3c-11ea-8a9f-f7639a29130b.png)

**Comment by tylim88** [comment]
I personally doubt that there is screen smaller than 576px (edit: there is, forgot about mobile)

nevertheless, I agree with fix since it can be easily solved and this button has no need to be flexible, I approved your commit and on top of that I apply my own fix, the width of sound button is now fixed-width rather than 100% width

https://github.com/zero-to-mastery/GameSenshi/commit/58f8fff89efb495b529dd6d0ffe38a5d122124ee
