### ISSUE TITLE
[BUG] star ratings on profile page not working properly

### ISSUE THREAD

**Issue by WilsonChai** [zero-to-mastery/GameSenshi#50]
#### Issue description
The profile page's star rating not working as intended when hovering the mouse over them in all resolutions. 
In all resolutions, the half star ratings would display slightly under the empty star containers.
For 991px and below, the mouse has to hover on or slightly below the star containers for the stars to display.
For 992px and above, the rating system ceases to work.
#### Steps to reproduce the issue
1. Hover mouse over empty star containers to rate.
#### What's the expected result?
-When the mouse hovers over the empty star containers, the half stars should display within containers. 
-The rating system should work for 992px and above.
#### What's the actual result?
-Half stars display slightly below the empty containers.
-The rating system ceases to work in resolutions 992px and above.
#### Additional details / screenshot
- ![Screenshot](https://user-images.githubusercontent.com/28215990/69466706-6d3df100-0d42-11ea-921f-c14be4970652.png)

**Comment by tylim88** [comment]
@kam773

**Comment by tylim88** [comment]
I decided to remove this rating system

as far as concerned, if a Senshi receive a low rating,  it reduces her likelihood to get an appointment

instead, we would implement other kinds of rating, such as number rating

for example, popularity rating that rate from 0 to 100,000 or maybe no limit

now the difference between number rating and star rating is, number rating is less discrete

for example in the eye of a client
1 star: "ok, this girl has only 1 star, then she must be bad"
1000 score: "this girl has only 1000 score, she is not soo popular"

it gives the client "not soo popular" impression, instead of "bad"

the point is, people are less responsive when the rating system is less discrete and less likely land in strong "bad" impression

but what about the opposite, how can it give a strong good impression? I believe people can be impressed with a high number

this is also because the popularity point is something that can be accumulated, so the client would also think that low popularity score may be due to being a new member but not being bad

this is different to star rating that also can be accumulated but averaged to only 0-5 stars

the point is, in a number system
low number: doesn't give Senshi bad impression, instead give impression lack of something (eg lack of popularity)
high number: give Senshi good impression of excellent at something

https://github.com/zero-to-mastery/GameSenshi/commit/a923c4b19bb1bb3ea7377cc5cdf92641222408ef
